analyzers:
  -
    command: "gosec"
    output_flag: "-out"
    install_command: "go install github.com/securego/gosec/v2/cmd/gosec@latest"
    as: "go"
  -
    command: "bandit"
    flags: "-r"
    output_flag: "--output"
    install_command: "pip install bandit"
    as: "python"