analyzers:
  -
    command: "gosec"
#    flags: "-out=\"output/gosec.txt\""
    flags: "-out=\"gosec.txt\""
    install_command: "go install github.com/securego/gosec/v2/cmd/gosec@latest"
  -
    command: "bandit"
#    flags: "-r"
    flags: "-r --output=\"output/bandit.txt\" -f txt"
    install_command: "pip install bandit"
#  -
#    command: "eslint"
#    flags: ""
#    install_command: "npm install -g eslint"
#  -
#    command: "phpstan"
#    flags: ""
#    install_command: "composer global require phpstan/phpstan"
